### PHYTIUM DEV SETTING START
export AARCH32_CROSS_PATH=${HOST_DIR}/opt/gcc-arm-none-eabi
export PATH=$PATH:${AARCH32_CROSS_PATH}/bin
export AARCH64_CROSS_PATH=${HOST_DIR}/opt/aarch64-none-elf
export PATH=$PATH:${AARCH64_CROSS_PATH}/bin
export PHYTIUM_DEV_PATH=${HOST_DIR}
### PHYTIUM DEV SETTING END
